repos:
  - repo: local
    hooks:
      - id: lines
        name: line counter and tokenizer
        entry: python src/tests/sz.py 
        language: system
        verbose: true
        always_run: true
        pass_filenames: false