repos:
  - repo: local
    hooks:
      - id: lines
        name: line counter and tokenizer
        entry: cargo test src/tests/sz
        language: system
        always_run: true
        pass_filenames: false
