on: [push, pull_request]

name: Test

jobs:
  test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - name:  checkout code
        uses: actions/checkout@v3
      - name: setup cargo
        uses: actions-rs/cargo@v1
        with:
          command: test lines -- --nocapture
